name: Java CI

on:
  workflow_dispatch:
    inputs:
      num:
        description: 'Integer number'
        required: true
        type: string
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: convert input to integer
       id: convert_input
       run: echo "::set-output name=num::${{ github.event.inputs.num }}"

     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: Build and run Java application
       run: |
        java EvenOdd.java ${{ steps.convert_input.outputs.num }}
